apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobserv-cli
  namespace: netobserv-cli
  labels:
    app: netobserv-cli
spec:
  selector:
    matchLabels:
      app: netobserv-cli
  template:
    metadata:
      labels:
        app: netobserv-cli
    spec:
      serviceAccountName: netobserv-cli
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: netobserv-cli
        image: "{{AGENT_IMAGE_URL}}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: METRICS_ENABLE
            value: "false"
          - name: LOG_LEVEL
            value: trace
          - name: ENABLE_PCA
            value: "true"
          - name: FILTER_DIRECTION
            value: ""
          - name: FILTER_IP_CIDR
            value: "0.0.0.0/0"
          - name: FILTER_PROTOCOL
            value: ""
          - name: FILTER_SOURCE_PORT
            value: ""
          - name: FILTER_DESTINATION_PORT
            value: ""
          - name: FILTER_PORT
            value: ""
          - name:  FILTER_SOURCE_PORT_RANGE
            value: ""
          - name: FILTER_DESTINATION_PORT_RANGE
            value: ""
          - name: FILTER_PORT_RANGE
            value: ""
          - name: FILTER_ICMP_TYPE
            value: ""
          - name: FILTER_ICMP_CODE
            value: ""
          - name: FILTER_PEER_IP
            value: ""
          - name: FILTER_ACTION
            value: "Accept"
          - name: TARGET_HOST
            value: "collector.netobserv-cli.svc.cluster.local"
          - name: TARGET_PORT
            value: "9999"
          - name: EXPORT
            value: "grpc"
